### ISSUE TITLE
Update Pub Package

### ISSUE THREAD

**Issue by DFazekas** [imujtaba8488/im_animations#3]
The latest version of the [pub package](https://pub.dev/packages/im_animations) is not null safe. Please update the package.

**Comment by xLusyo** [comment]
Truly a great package. Need a null safe version.

**Comment by imujtaba8488** [comment]
Hi @DFazekas @xLusyo ... Thank you for the feedback. The null safe is already available from GitHub. However, I will update it in pub.dev as soon as I get sometime.

Thank you!

**Comment by imujtaba8488** [comment]
@DFazekas @xLusyo updated on pub.dev -- Thank you for the patience!
